# Generated by Django 5.2.8 on 2025-12-18 19:24

import Dispatch_taxi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatch_taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, validators=[Dispatch_taxi.models.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=12, validators=[Dispatch_taxi.models.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='driver_license',
            field=models.CharField(max_length=10, unique=True, validators=[Dispatch_taxi.models.validate_driver_license], verbose_name='Водительское удостоверение'),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[Dispatch_taxi.models.validate_url], verbose_name='Фото водителя'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='phone',
            field=models.CharField(max_length=12, validators=[Dispatch_taxi.models.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=15, unique=True, validators=[Dispatch_taxi.models.validate_license_plate], verbose_name='Номерной знак'),
        ),
    ]
